# -*- coding: utf-8 -*-
"""Baitaplab01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n4zgG5eT-UEoT2lD_0bb7yJbt-rD4lIW
"""

#W2A1
print("hello world")

#W2A2
name = input("Nhập họ tên của bạn: ")
print("Xin chào", name, "đẹp trai xinh gái!")

#W2A10
name_list = input("Nhập tên 3 người: ").split()
name_list.reverse()
print(name_list[0],name_list[1], name_list[2] )

#W2A16
print("Spring\nSummer\nFall\nWinter")

#W2A17
for i in range(1,6,2):
  print("*"*i)

#W2A18
print('''### # #   ### ###
 #  #  #   #   #
 #  #   #  #   #
 #  #  #   #   #
 #  # #    #   #''')

#W2A19
days = ("Monday Tuesday Wednesday Thursday Friday Saturday Sunday").split()
for day in days:
  print(day)

#W2A20
months = ("January February March April May June July August September October November December").split()
for month in months:
  print(month)