# -*- coding: utf-8 -*-
"""buoi6_09_12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15knhB2uZjFsXx-zBUNtKT0g0t0J78wJc
"""

#W6A1
nums = list(map(int, input().split()))
a = []
for i in nums:
  if i not in a:
    a.append(i)
print(a)

#W6A2
nums = list(map(int, input().split()))
a = 0
tong = []
for ch in nums:
  a += ch
  tong.append(a)
print(tong)

#W6A3
nums = tuple(map(int, input().split()))
k = int(input())
k = k % len(nums)
result = nums[k:] + nums[:k]
print(result)

#W6A4
a = input().split()
b = {}
for pairs in a:
  key, value = pairs.split(':')
  b[key] = b.get(key, []) + [value]
print(b)

#W6A5
nums = list(map(int, input().split()))
b = {'negatives':0, 'positives':0, 'zeros':0}
for i in nums:
  if i < 0:
    b['negatives'] += 1
  if i > 0:
    b['positives'] += 1
  if i == 0:
    b['zeros'] += 1
print(b)

#W6A6
nums = list(map(int, input().split()))
print(sum(nums))

#W6A7
nums = tuple(input().split())
reverse = ()
for i in range(len(nums)):
  reverse = (nums[i],) + reverse
print(nums[0], nums[-1], reverse)

#W6A8
sequence = list(input().split())
frq = {}
for word in sequence:
  frq[word] = frq.get(word, 0) + 1
print(frq)

#W6A9
import ast
d1 = ast.literal_eval(input())
d2 = ast.literal_eval(input())
result = {}
for key, value in d1.items():
  result[key] = value
for key, value in d2.items():
  result[key] = result.get(key, 0) + value
print(dict(sorted(result.items())))

#W6A10
nums = tuple(map(int, input().split()))
k = int(input())
b = []
for i in range(len(nums) - 1):
  for u in range(i + 1, len(nums)):
    if nums[i] + nums[u] == k:
      if (nums[i],nums[u]) not in b:
        b.append((nums[i],nums[u]))
print(sorted(b))

#W6A11
nums = tuple(map(int, input().split()))
a = ()
b = ()
for i in nums:
  if i % 2 == 0:
    a += (i,)
  else:
    b += (i,)
print(a)
print(b)

#W6A12
nums = sorted(list(map(int,input().split())))
b = {}
max = 0
for i in nums:
  b[str(i)] = b.get(str(i), 0) + 1
for key, value in b.items():
  if b[key] > max:
    max = value
    k = key
print(k)

#W6A13
char = list(input().split())
b = {}
for i in range(len(char)):
  if i % 2 == 0:
    b[char[i+1]] = char[i]
print(b)

#W6A14
nums1 = list(map(int, input().split()))
nums2 = list(map(int, input().split()))
b = []
for i in nums1:
  for k in nums2:
    if i == k and i not in b:
      b.append(i)
print(b)

#W6A15
char = list(input().split())
k = int(input())
b = {}
for i in range(len(char)):
  if i % 2 == 0:
    b[char[i]] = int(char[i+1])
    if b[char[i]] <= k:
      b.pop(char[i])
print(b)

#W6A19
nums = list(map(int, input().split()))
k = max(nums)
for i in range(len(nums)):
  if nums[i] == k:
    print(i + 1)

#W6A20
nums = list(map(int, input().split()))
k = int(input())
def vitri(a):
  for i in range(len(a)):
    if a[i] == k:
      return i + 1
  return -1
print(vitri(nums))

#W6A21
nums = list(input().split())
b = {}
for i in range(len(nums)):
  b[nums[i]] = b.get(nums[i], ()) + (i,)
print(b)

#W6A22
nums = list(map(int, input().split()))
k = max(nums)
for i in range(len(nums)):
  if nums[i] == k:
    print(i + 1)