# -*- coding: utf-8 -*-
"""Baitaplab012.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15iwwByjwhJBuPxPVe83ONVFXpxb1IAj1
"""

#W2A1
print("hello world")

#W2A2
name = input("Nhập họ tên của bạn: ")
print("Xin chào", name, "đẹp trai xinh gái!")

#W2A3
a= int(input('Nhap so nguyen a: '))
b= int(input('Nhap so nguyen b: '))
c_cong= a+b
print('Tong hai so a va b la: ',c_cong)
c_tru= a-b
print('Hieu hai so a va b la: ',c_tru)
c_nhan= a*b
print('Tich hai so a va b la: ',c_nhan)
c_chia_nguyen= a//b
print('Thuong nguyen hai so a va b la: ',c_chia_nguyen)
c_chia_du= a%b
print('Thuong du hai so a va b la: ',c_chia_du)
c_chia= a/b
print('Thuong hai so a va b la: ', '%.2f'%c_chia)

#W2A4
a,b,c,a2,b2,a3 = map(int, input('Nhap diem so: ').split())
a2 *= 2
b2 *= 2
a3 *= 3
trung_binh = (a + b + c + a2 + b2 + a3)/10
print('Diem trung binh cua ban la: ', '%.2f'%trung_binh)

#W2A5
so = input('Nhap hai so a va b: ').split()
a= int(so[0])
b= int(so[1])
c = a**b
print('a mu b la: ',c)

#W2A6
chu_thuong = input('Nhập một chữ cái thường a-z: ')
ma_unicode = ord(chu_thuong)
print('Mã Unicode của nó là', ma_unicode )
chu_hoa = chr(ma_unicode - 32)
print('ki tu hoa tuong ung cua no la', chu_hoa)

#W2A7
A = ((13 ** 2) * 3) + 5
print(A)
B = 13 ** 2 * 3 + 5
print(B)

#W2A8
c = float( input( 'Nhiệt độ theo độ C: '))
f = (9 / 5) * c + 32
print(c, 'do C tương ứng với ',f , 'độ F')

#W2A9
gia = int(input('Đồng hồ trị giá ($): '))
print('Anh Đặt phải trả', gia * 1.4 + 10 ,'$ để mua chiếc đồng hồ đó')

#W2A10
name_list = input("Nhập tên 3 người: ").split()
name_list.reverse()
print(name_list[0],name_list[1], name_list[2] )

#W2A11
h = int(input('Số giờ: '))
m = int(input('Số phút: '))
print(h, 'giờ', m, 'phút bằng', 3600 * h + 60 * m, 'giây')

#W2A12
n = int(input('Độ dài cạnh khối rubik là: '))
print('Cần', n ** 2 * 6, ' miếng dán riêng lẻ để bao phủ toàn bộ khối lập phương')

#W2A13
a, b = map(int, input('Nhập 2 số nguyên dương a và b ').split())
tich_donvi = (a * b) % 10
print('Hàng đơn vị của tích a và b là ', tich_donvi)

#W2A14
a, b = map(int, input('Nhập 2 số nguyên dương a và b ').split())
a, b = b, a
print (a,b)

#W2A15
n = int(input('Nhập vào một số nguyên dương: '))
print('Số sao thứ', n, 'là: ', 1 + 6 * n * (n - 1)) #Công thức tự chứng minh được

#W2A16
print("Spring\nSummer\nFall\nWinter")

#W2A17
for i in range(1,6,2):
  print("*"*i)

#W2A18
print('''### # #   ### ###
 #  #  #   #   #
 #  #   #  #   #
 #  #  #   #   #
 #  # #    #   #''')

#W2A19
days = ("Monday Tuesday Wednesday Thursday Friday Saturday Sunday").split()
for day in days:
  print(day)

#W2A20
months = ("January February March April May June July August September October November December").split()
for month in months:
  print(month)

#W2A21
for i in range(1,11):
  print('Hello, world')

