# -*- coding: utf-8 -*-
"""Buoi5_25_11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LIOL_Glfiqd8LFs27eF1OL1eJxRwNRDF
"""

#W5A1
def Max_Of_Two(a,b):
  return max(a,b)
a,b = map(int, input("Nhập hai số a và b: ").split())
Max_Of_Two(a,b)

#W5A2
def swap(a,b):
  return b, a
a,b = map(int, input("Nhập hai số a và b: ").split())
a,b = swap(a,b)
print(a,b)

#W5A3
from math import sqrt
def prnum(a):
  if a > 1:
    for i in range (2, int(sqrt(a)) + 1):
      if a % i == 0:
        return False
    return True
  else:
    print('Nhập số lớn hơn hoặc bằng 2')
n = int(input('Nhập số nguyên tố: '))
prnum(n)

#W5A4
def shh(a):
  tong_uoc = 0
  for i in range (1, int(a / 2) + 1):
    if a % i == 0:
      tong_uoc += i
  if tong_uoc == a:
    return True
  return False
n = int(input('Nhập số hoàn hảo: '))
shh(n)

#W5A5
def abc():
  a = list(map(int, input('Nhap day so nguyen ').split()))
  b = int(input('Nhap so nguyen '))
  for i in range (0, len(a)):
    if a[i] == b:
      return i + 1
  return -1
abc()

#W5A6
def gt(n):
  gt = 1
  for i in range(1 , n + 1):
    gt *= i
  return gt
a = int(input('Nhap so nguyen duong '))
gt(a)

#W5A7
def cal():
  a, b, c = input('Nhập phép toán ').split()
  if b == '+':
    kq = float(a) + float(c)
  if b == '-':
    kq = float(a) - float(c)
  if b == '*':
    kq = float(a) * float(c)
  if b == '/':
    kq = float(a) / float(c)
  return print(f"{kq:.2f}")
cal()

#W5A8
def hamming(a,b):
  a,b = str(bin(a)[2:]) , str(bin(b)[2:])
  ham = 0
  if len(a) == len(b):
    for i in range(0, len(a)):
      if a[i] != b[i]:
        ham += 1
    return ham
  elif len(a) > len(b):
    for i in range(0,len(b)):
      if b[i] != a[i+ (len(a) - len(b))]:
        ham += 1
    for i in range(0,len(a) - len(b)):
      if a[i] == '1':
        ham += 1
    return ham
  else:
    for i in range(0,len(a)):
      if a[i] != b[i+ (len(b) - len(a))]:
        ham += 1
    for i in range(0,len(b) - len(a)):
      if b[i] == '1':
        ham += 1
    return ham

a,b = map(int, input('Nhập số nguyên a,b:').split())
hamming(a,b)

#W5A9
def sum(a):
  tong = 0
  for i in range(0,len(str(a))):
    tong += (a % 10)
    a = a // 10
  return tong
b = int(input('Nhap so nguyen '))
sum(b)



#W5A10
def anh_xa(a,b):
  atob = {}
  btoa = {}

  for A,B in zip(a,b):
    if A in atob:
      if atob[A] != B:
        return False
    if B in btoa:
      if btoa[B] != A:
        return False
    atob[A] = B
    btoa[B] = A
  return True
x,y = input().split()
anh_xa(x,y)